# Generated by Django 4.1 on 2023-06-17 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='message',
            new_name='payload',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_bot',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_last',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='options',
        ),
    ]
