# Generated by Django 4.1 on 2023-04-17 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_super'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='super',
            field=models.CharField(choices=[('head', 'Head'), ('top', 'Top'), ('bottom', 'Bottom'), ('foot', 'Foot'), ('extra', 'Extra')], default='top', max_length=20),
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isApproved', models.BooleanField(default=True)),
                ('bottom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottoms', to='api.apparel')),
                ('foot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footwear', to='api.apparel')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tops', to='api.apparel')),
            ],
            options={
                'verbose_name_plural': 'Outfits',
            },
        ),
    ]
